upstream lamport_cluster {
    least_conn;

    server lamport-server-1:5000;
    server lamport-server-2:5000;
    server lamport-server-3:5000;
}

server {
    listen 80;

    server_name _;

    location / {
        proxy_pass http://lamport_cluster;

        # WebSocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        # Headers úteis
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Timeout websocket
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }
}